rmdir /S /Q Debug
rmdir /S /Q ipch
rmdir /S /Q Release
del /F /S *.sdf

rmdir /S /Q WorldShaper\Debug
rmdir /S /Q WorldShaper\Release

rmdir /S /Q Application\Debug
rmdir /S /Q Application\Release

rmdir /S /Q GameObjectManager\Debug
rmdir /S /Q GameObjectManager\Release

rmdir /S /Q ModelManager\Debug
rmdir /S /Q ModelManager\Release

rmdir /S /Q ShaderManager\Debug
rmdir /S /Q ShaderManager\Release

rmdir /S /Q TextureManager\Debug
rmdir /S /Q TextureManager\Release

rmdir /S /Q UnitTests\Debug
rmdir /S /Q UnitTests\Release

